[linters]
  enable-all = true
  disable = [
    "lll",
    "gochecknoglobals",
    "exhaustivestruct",
    "noctx",
    "gomnd"
  ]

[issues]
    exclude-use-default = true
    [[issues.exclude-rules]]
        path = "api.go"
        text = "Potential HTTP request made with variable url"