apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cloudflare-ddns.fullname" . }}
  labels:
    {{- include "cloudflare-ddns.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronSchedule | quote }}
  concurrencyPolicy: "Forbid" # stop two jobs from running at the same time
  failedJobsHistoryLimit: 1 # how many failed jobs to keep so you can look at the logs
  successfulJobsHistoryLimit: 1 # how many successful jobs to keep so you can look at the logs
  startingDeadlineSeconds: 60 # 1 min
  jobTemplate:
    metadata:
      name: {{ include "cloudflare-ddns.fullname" . }}
      labels:
        {{- include "cloudflare-ddns.labels" . | nindent 8 }}
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "cloudflare-ddns.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          serviceAccountName: {{ include "cloudflare-ddns.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext: {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
              - secretRef:
                  name: {{ include "cloudflare-ddns.fullname" . }}-env
              {{- with .Values.extraEnvFrom }}
                {{- toYaml . | nindent 14 }}
              {{- end }}

              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
