apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns
  namespace: argocd
spec:
  destination:
    namespace: cloudflare-ddns
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: image.tag
        value: ${ARGOCD_APP_REVISION}
      - name: nameOverride
        value: cloudflare-ddns
      - name: fullnameOverride
        value: cloudflare-ddns
      - name: extraEnvFrom[0].secretRef.Name
        value: env-from-terraform
    path: deploy/helm/cloudflare-ddns
    repoURL: https://github.com/oliverisaac/cloudflare-ddns
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
