apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-ddns.fullname" . }}-env
  labels:
    {{- include "cloudflare-ddns.labels" . | nindent 4 }}
stringData:
  {{ range $key, $value := .Values.env }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

