name: Build

on:
  pull_request
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.6"
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34
          skip-go-installation: true
