name: Release

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Docker Image Names
        id: image_names
        env:
          TAGS: ${{ github.sha }},latest
          FULL_REPO_NAME: ${{ github.repository }}
          DOCKERHUB_NAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |-
          image_name="${DOCKERHUB_NAME}/${FULL_REPO_NAME##*/}"
          all_tags=()
          for tag in ${TAGS//,/ }; do
            all_tags+=( "$image_name:$tag" )
          done
          echo "names=$( printf "%s," "${all_tags[@]}" | sed 's/,$//' )" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.image_names.outputs.names }}
