name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Note the fetch-depth: 0 option is required for the change log to
          # work correctly with goreleaser.
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.15.6"
      - uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.45.2
      - name: Unit testing
        run: go test ./...

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Docker Image Names
        id: image_names
        env:
          TAGS: ${{ github.sha }},latest
          FULL_REPO_NAME: ${{github.repo}}
          DOCKERHUB_NAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |-
          image_name="${DOCKERHUB_NAME}/${FULL_REPO_NAME##*/}"
          all_tags=()
          for tag in ${TAGS//,/ }; do
            all_tags+=( "$image_name:$tag" )
          done
          echo ::set-output name=names::$( printf "%s," "${all_tags[@]}" | sed 's/,$//' )

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.image_names.outputs.names }}
